config: !!python/object:argparse.Namespace
  AT: 16
  T: 64
  additional_epoch: 20
  batch_size: 64
  data_format: eeg
  dataset: FATIG
  dropout: 0.5
  full_run: 0
  gpu: 0
  graph_type: BL
  kernel_length: 13
  label_type: FTG
  load_path: ./data_processed/
  lr: 0.001
  max_epoch: 200
  mixed_precision: 0
  model: Deformer
  num_chan: 30
  num_class: 2
  num_layers: 6
  num_time: 384
  overlap: 0
  random_seed: 2023
  sampling_rate: 128
  save_path: ./save/
  segment: 4
  subjects: 11
  test_sub: 0
  trial_duration: 60
  val_rate: 0.2
